version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    command: >
      sh -c "while ! nc -z db 5432; do sleep 0.1; done;
             psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres < ./create_database.sh"
  jivsek:
    image: jivsek
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db:
    driver: local

