version: '3.4'

services:
  jivsek:
    image: jivsek
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 8080:8080
      - 5678:5678
    environment:
      - FLASK_APP=./sreality/sreality/spiders/app.py
